### ISSUE TITLE
failed to decode event

### ISSUE THREAD

**Issue by sergeibadass** [itering/subscan-essentials#100]
Hi I am running with node-template and managed to decode extrinsic of custom pallets.

However, events of such pallets can not be properly encoded. Errors were thrown at this block of codes at block.go:
![image](https://user-images.githubusercontent.com/76840075/106283959-88c55580-627d-11eb-812b-2734d3c09b01.png)

May I ask how does substrate decodes custom event types in general? as those are not defined in the types.json?

And how to fix this problem in the scope of subscan-essentials?

Thanks Subscan team.

**Comment by zoheb391** [comment]
Hi @sergeibadass, did you ever figure this out?
