### ISSUE TITLE
polkadot 区块链浏览器数据不对

### ISSUE THREAD

**Issue by zyjblockchain** [itering/subscan-essentials#102]
polkadot tx hash: 0x833bd75719a2a16c456db195165dbe5c4b6617f3465a98bf8a005485889321e2

在 subscan 中查询到的数据：
![image](https://user-images.githubusercontent.com/40423181/106769334-cb20d500-6677-11eb-8a38-c0b2984a2458.png)
在polkascan 查询到的数据：
![image](https://user-images.githubusercontent.com/40423181/106769419-e7247680-6677-11eb-9879-cfc1cded9d65.png)

我本地同步到的数据和polkascan 上查询的数据一致，所以可能死subscan 这边出问题了

**Comment by freehere107** [comment]
谢谢反馈，我查看一下

**Comment by freehere107** [comment]
因为 substrate 底层nonce可能会重置，所以 tx hash 可能是不唯一的, 请使用 extrinsic index 进行索引。
https://polkadot.subscan.io/extrinsic/2935386-1
