### ISSUE TITLE
westend 解析与subscan浏览器信息对不上

### ISSUE THREAD

**Issue by 1042782229** [itering/subscan-essentials#105]
![image](https://user-images.githubusercontent.com/13817276/108944206-4719a600-7695-11eb-9e47-6eb42bab53d0.png)
![image](https://user-images.githubusercontent.com/13817276/108944273-657fa180-7695-11eb-9e43-8f71f06b4b56.png)
https://westend.subscan.io/extrinsic/0x434ec948989ef93699c76e18aa9773283c751d5b8f50325dc5e712482d78e18b

**Comment by freehere107** [comment]
@1042782229  Westend 网络runtime 已经更新，需要更新 type json https://github.com/itering/subscan-essentials/blob/master/configs/source/westend.json

**Comment by 1042782229** [comment]
解决了  谢谢  @freehere107
