### ISSUE TITLE
incorrect finalized block hash for polkadot 3,904,932

### ISSUE THREAD

**Issue by ianhe8x** [itering/subscan-essentials#106]
From the archieve node I ran and also rpc.polkadot.io, the blockhash of polkadot 3,904,932 is 0xeb488188b1ff0af4ff59445c5e3ce964b654608a967fc8c042111e8d429000dc

but if you check https://polkadot.subscan.io/block/3904932?tab=extrinsic
it shows differently 0x18129c897d0a861a6ea7fe65ad11c5d1fed960fcb67fd86ab9afe5e19e067d50

**Comment by freehere107** [comment]
@ianhe8x Thank you feedback, We will fix it right away

**Comment by freehere107** [comment]
It has been fixed, thanks for your feedback
