### ISSUE TITLE
substrate 3.0 indexing break

### ISSUE THREAD

**Issue by sergeibadass** [itering/subscan-essentials#107]
HI I recently upgrade my substrate impl from 2.0 to 3.0 and now the subscan-essential breaks with decoding errors of events and extrinsic. 

Is there any breaking change of substrate 2.0 to 3.0 with respect to subscan (e.g. scale codec change)? Does the new subscan version support 3.0 already? thanks.

**Comment by sergeibadass** [comment]
@freehere107 

![image](https://user-images.githubusercontent.com/76840075/110293077-10df0d80-8029-11eb-8ae4-92529b8dd947.png)

These types are missing with scale.codec v1.0.8. substrate core v3.0.

Could you please help debug it?Thanks.

**Comment by freehere107** [comment]
@sergeibadass Can you provide some error logs obtained?
