### ISSUE TITLE
批量同步区块偶现交易记录丢失问题

### ISSUE THREAD

**Issue by zyjblockchain** [itering/subscan-essentials#113]
问题描述：
1. 当连接的节点停摆一段时间之后（1 小时）
2. 节点恢复之后，再次启动程序去同步区块
3. 发现区块同步下来了，但是部分区块中的交易没有解析到数据库或者是存在解析到数据库的交易数据有误

请问大家有发现过这个问题吗。

**Comment by chrisli30** [comment]
> 问题描述：
> 
> 1. 当连接的节点停摆一段时间之后（1 小时）
> 2. 节点恢复之后，再次启动程序去同步区块
> 3. 发现区块同步下来了，但是部分区块中的交易没有解析到数据库或者是存在解析到数据库的交易数据有误
> 
> 请问大家有发现过这个问题吗。

你这是指哪个链的节点？

**Comment by zyjblockchain** [comment]
> > 问题描述：
> > 
> > 1. 当连接的节点停摆一段时间之后（1 小时）
> > 2. 节点恢复之后，再次启动程序去同步区块
> > 3. 发现区块同步下来了，但是部分区块中的交易没有解析到数据库或者是存在解析到数据库的交易数据有误
> > 
> > 请问大家有发现过这个问题吗。
> 
> 你这是指哪个链的节点？

polkadot kusama 都存在

**Comment by freehere107** [comment]
是可能会因为数据库问题，节点问题导致数据获取不成功，因此需要加一些额外的worker 去resync block
