### ISSUE TITLE
Is there an endpoint to search for all transactions of an account?

### ISSUE THREAD

**Issue by chrisli30** [itering/subscan-essentials#126]
I see this API `POST /api/v2/scan/search`, but there's no transaction list in the response.

Two other questions:
1. Is it possible to search for all transactions to a particular pallet?
1. What do the `key` and `row` mean in `POST /api/scan/search`?

Thanks.

**Comment by freehere107** [comment]
``/api/scan/search``` only support serach account.

``key`` and ``row``  has been discarded

Get transactions you can use this  https://docs.api.subscan.io/#extrinsics

**Comment by chrisli30** [comment]
Ah I see the events in extrinscis response. Cool, this issue is answered 👍
