### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by kylezs** [itering/subscan-essentials#128]
I've tried following the README, but it doesn't work, and a bunch of links are broken.

Is it outdated?

If I want to run all the components with docker compose what needs to change?

Following the README I can get up to the `docker compose up` step, but running `docker compose up` throws:
`no such service: mysql`

The mysql container is definitely running, as the `docker-compose.db.yml` works and I can see it running as:
`subscan-essentials_mysql_1` when I run `docker ps`

**Comment by anizeani** [comment]
try to clean up your docker environment:
docker system prune
docker system prune -a
docker volum prune 
(always choose yes to clean up)
and then redo the readme

**Comment by kylezs** [comment]
@anizeani 
Thanks, that at least got the containers running.

Seems there's still a bunch of things to change, which aren't in the README. need to change the front end port so it's not 80. 
And now after I can see the frontend, it shows `Connection refused`  when trying to hit any of the endpoints on`http://127.0.0.1:4399` which is where the `subscan-essentials_subscan-observer_1` container is running. Guessing there's some more config required not described in the README ?

**Comment by anizeani** [comment]
yes, I have the same issue. I can't reach the endpoint either. 
why did you change the front end port? if 80 is not blocked by another app, it should work (it works for me)

**Comment by kylezs** [comment]
For some reason 80 was blocked, might be a mac thing? idk, worked when I changed it anyway.

I noticed that when I start the containers, I get:
```
e55c3d3164f5   6c4583c15f6b   "/tini -- python run…"   10 minutes ago   Up 10 minutes   4399/tcp
```
The port is not being mapped outside, not sure why because the other containers do, but this one doesn't and the config looks the same to me.

**Comment by kylezs** [comment]
Looks like the api container wasn't actually starting, was crashing on startup, couldn't find subscan database :/

**Comment by kylezs** [comment]
Linking: https://github.com/itering/subscan-essentials/issues/131

**Comment by kylezs** [comment]
Ok, after some time, I'm now getting the `no such service: mysql` error again, and pruning my docker env isn't helping

**Comment by kylezs** [comment]
https://github.com/itering/subscan-essentials/issues/131

My comments / PR there worked. Worth putting this in the README?
