### ISSUE TITLE
[Feature Request] Show Total # of Nominators / Validators as statistics

### ISSUE THREAD

**Issue by shawntabrizi** [itering/subscan-essentials#134]
It would great to see how many total nominators and validators there are on chain when viewing the staking section of Subscan.

🙏

**Comment by freehere107** [comment]
@shawntabrizi https://kusama.subscan.io/validator How many Validators have been shown here, right?

**Comment by freehere107** [comment]
There is no API to get the number of total nominators directly, but you can use https://docs.api.subscan.io/#validators to add up the nominators of all validators
