### ISSUE TITLE
API Call on bond extrinsic returns params as string

### ISSUE THREAD

**Issue by jonasW3F** [itering/subscan-essentials#137]
The API call for the bond extrinsic (and at least for bond_extra and unbond) returns the specifics of the "params" as a string. This makes it a bit annoying to work with as the "value" of the calls is encoded in there and varies in size.

Maybe that is an error and it was supposed to be encoded as an object?

**Comment by freehere107** [comment]
@jonasW3F Yes, there are some historical reasons for this, but the API is currently used by a large number of users, and some structural adjustments cannot be easily made. Here we will make changes in the v2 version.

**Comment by jonasW3F** [comment]
okay, thanks
