### ISSUE TITLE
Extrinsic value sometimes is not decoded in latest version

### ISSUE THREAD

**Issue by Yuripetusko** [itering/subscan-essentials#152]
Example here
https://kusama.subscan.io/extrinsic/0x596a166ee1fb01e6d9f0940340f0b958c6cbcb2d6b21f00408cb2718a7efc4de

extrinsic of type system.remark used to be displayed decoded before but not anymore 

![image](https://user-images.githubusercontent.com/666169/131809655-19b56fa3-f46a-4222-bea8-f84d794f8433.png)

**Comment by freehere107** [comment]
@Yuripetusko Hi, system.remark context not decoded because it not ascill

**Comment by Yuripetusko** [comment]
It used to be shown decoded just few weeks ago, by decoded I mean polkadot js hextToString method. Most of the time system remark contains some kind of message so it would be nice to display it here instead of hex. And subscan used to do it not a long time ago,nso it's a new bug

**Comment by freehere107** [comment]
> It used to be shown decoded just few weeks ago, by decoded I mean polkadot js hextToString method. Most of the time system remark contains some kind of message so it would be nice to display it here instead of hex. And subscan used to do it not a long time ago,nso it's a new bug

Hey, Yuripetusko , I check polkadot js  https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpub.elara.patract.io%2Fkusama#/explorer/query/9041075, the same is shown here, there may be some characters that cannot be decoded

**Comment by Yuripetusko** [comment]
Oh yeah, you are right. Interesting, will try to investigate this more locally
