### ISSUE TITLE
Subidentities are not displayed on Subscan for Shiden chain

### ISSUE THREAD

**Issue by Poggi-Luca** [itering/subscan-essentials#153]
Hello, the following Shiden addresses:
- [XoY6Qh7bpmhe8h3h5aR1GbQA3ee7Aj7zKsCxBhR2RC8JULE](https://shiden.subscan.io/account/XoY6Qh7bpmhe8h3h5aR1GbQA3ee7Aj7zKsCxBhR2RC8JULE)
- [W8PzksJcA1Ag82GNvuxT6Ejp4KXqQexNXqysJyuxSvHSmH9](https://shiden.subscan.io/account/W8PzksJcA1Ag82GNvuxT6Ejp4KXqQexNXqysJyuxSvHSmH9)
are :ice_cube: Iceberg Nodes :ice_cube: / C2 and :ice_cube: Iceberg Nodes :ice_cube: / C3 respectively.

The master identity is [Yr7ZxQJX6Ho4qBFywoA5hvFSxpBtLQv5T4LnLpzy3MffKJa](https://shiden.subscan.io/account/Yr7ZxQJX6Ho4qBFywoA5hvFSxpBtLQv5T4LnLpzy3MffKJa) as :ice_cube: Iceberg Nodes :ice_cube: and C1, C2 and C3 are subidentities for Collator 1, Collator 2 and Collator 3.
No displaying issues for [WywoJ3jqnpCeFchBV3dJpjHWhDiD2C5UaDm2Nk4FaV2aNLi](https://shiden.subscan.io/account/WywoJ3jqnpCeFchBV3dJpjHWhDiD2C5UaDm2Nk4FaV2aNLi) as C1, but for C2 and C3 the identity is not appearing on Subscan.

No problems on Polkadot JS Wallet App

**Comment by freehere107** [comment]
ok，thank you feedback，i will fix it soon

**Comment by freehere107** [comment]
It has been fixed

**Comment by Poggi-Luca** [comment]
Thank you! :+1:

**Comment by Poggi-Luca** [comment]
@freehere107 the same issue is present on Shibuya for WywoJ3jqnpCeFchBV3dJpjHWhDiD2C5UaDm2Nk4FaV2aNLi (it should be ice_cube Iceberg Nodes ice_cube / C1

Addresses and identity are the same on Shiden and Shibuya (please see at first message)

Thank you!
