### ISSUE TITLE
Update scale.go

### ISSUE THREAD

**Issue by alexqrid** [itering/subscan-essentials#154]
I see you update `scale.go` library, but the version of `substrate-api-rpc` (v0.4.0) that `subscan` depends on uses `scale.go` of v1.0.51 which is pretty old release. Do I need to update `scale.go` before starting to use `subscan` indexer or it will work with an old version of `scale.go? @freehere107

**Comment by freehere107** [comment]
@alexqrid ``substrate-api-rpc`` has been update https://github.com/itering/substrate-api-rpc
