### ISSUE TITLE
How do i get an updated list of endpoints?

### ISSUE THREAD

**Issue by johnuopini** [itering/subscan-essentials#155]
Is there a JSON, an API or something that will give me a list of the endpoints?
Or should i keep the list manually?
Thanks!

**Comment by freehere107** [comment]
endpoint currently does not have an api, you can view it here

**Comment by johnuopini** [comment]
> endpoint currently does not have an api, you can view it here

Thanks but here where?

**Comment by freehere107** [comment]
> > endpoint currently does not have an api, you can view it here
> 
> 
> 
> Thanks but here where?

https://docs.api.subscan.io/#api-endpoints
