### ISSUE TITLE
Invalid Request

### ISSUE THREAD

**Issue by EDUARD-EASY** [itering/subscan-essentials#157]
Hello everyone,

I'm trying to use subscan-essentials with a frontier template. I've been able to install it and connect with the frontier.
I've used "./target/release/frontier-template-node --dev --tmp --port 21000 --ws-port 22000 --rpc-port 8443 --validator --rpc-methods" to run the frontier and changed the target and browserBaseURL to http://127.0.0.1:8443.

When I try to scan it the output always give me the same error:

`{
jsonrpc: "2.0",
error: {
code: -32600,
message: "Invalid request"
},
id: null
}`

**Comment by freehere107** [comment]
@EDUARD-EASY port 8843 is ``http`` port, 22000 is websocket `port`

**Comment by EDUARD-EASY** [comment]
I know, but I've tried all combinations (ws://127.0.0.1:22000, http://127.0.0.1:22000, wss://127.0.0.1:22000, localhost, 0.0.0.0 ...).
And the frontier give me the same error:

![image](https://user-images.githubusercontent.com/85928275/134473745-b10a25fd-ba77-4f01-884c-9e4a37f2f9d1.png)

**Comment by freehere107** [comment]
> I know, but I've tried all combinations (ws://127.0.0.1:22000, http://127.0.0.1:22000, wss://127.0.0.1:22000, localhost, 0.0.0.0 ...).
> And the frontier give me the same error:
> 
> ![image](https://user-images.githubusercontent.com/85928275/134473745-b10a25fd-ba77-4f01-884c-9e4a37f2f9d1.png)



``ws://127.0.0.1:22000``  is  substrate client websocket rpc host, you can use this https://github.com/vi/websocat

**Comment by EDUARD-EASY** [comment]
I don't understand what I'm supposed to do with websocat. Don't I have to connect subscan essential with the substrate client websocket rpc host?

**Comment by freehere107** [comment]
Set this env https://github.com/itering/subscan-essentials/blob/master/util/env.go#L13 use  ``ws://127.0.0.1:22000``
