### ISSUE TITLE
Too much differnces & different source "account_id" against public version

### ISSUE THREAD

**Issue by jun0tpyrc** [itering/subscan-essentials#166]
Left : 
```
curl --location --request POST 'https://shiden.api.subscan.io/api/scan/block' --header 'Content-Type: application/json' --data-raw '{ "block_num": 618465 }' | jq
```
Right:
Private hosted version on same block indexed using https://github.com/itering/scale.go/blob/master/network/shiden.json

<img width="1677" alt="Screenshot 2021-11-06 at 7 44 42 AM" src="https://user-images.githubusercontent.com/68580727/140589836-4b1a04a9-c4f5-4e4f-85f8-1ef370791d35.png">
<img width="1792" alt="Screenshot 2021-11-06 at 7 26 39 AM" src="https://user-images.githubusercontent.com/68580727/140589698-eb7f1667-ce92-4d6b-ab64-9e40a431b1e3.png">
<img width="1792" alt="Screenshot 2021-11-06 at 7 26 55 AM" src="https://user-images.githubusercontent.com/68580727/140589700-a397752b-fb18-4191-9aaf-af59b84ea642.png">
<img width="1792" alt="Screenshot 2021-11-06 at 7 27 03 AM" src="https://user-images.githubusercontent.com/68580727/140589702-0cb7fd44-de6c-4d3c-8b1f-e52b460a5703.png">

- multiple field differences
- in balances.transfer `account_id` being different....

**Comment by jun0tpyrc** [comment]
Private versions running on
```
commit 6400a20d84b9b74afedb5c81d02044fc22202859 (HEAD -> master, origin/master, origin/HEAD)
Author: freehere107 <freehere107@gmail.com>
Date:   Mon Oct 25 09:34:46 2021 +0800

    Fix BlockTimestamp is compact<U64>
```

**Comment by freehere107** [comment]
@jun0tpyrc Yes, The open source version is just a basic version
