### ISSUE TITLE
Sub identity is not displayed correctly

### ISSUE THREAD

**Issue by Poggi-Luca** [itering/subscan-essentials#170]
Hello, the following sub identities are not displayed correctly (the super identity is missing):
- Polkadot: 14ices1G5qTmqhMfDVBECh4jotNDGTLu8fhE9YktWT3cLF2F
- Kusama: Eices1KaGTYqiazfjJpwyjnz5UzqTxULeYqnmeJNz49gs19
Please, could you kindly check?
Thank you

**Comment by freehere107** [comment]
@Poggi-Luca We have fixed this problem, thank you for your feedback
