### ISSUE TITLE
Display the token contract address build on Crab EVM.

### ISSUE THREAD

**Issue by 1022ranji** [itering/subscan-essentials#172]
Could you please display the token address built on Crab/Pangolin EVM? There are some tokens in EVM but users cannot search their contract addresses.
![image](https://user-images.githubusercontent.com/80877629/145376251-86f52b9b-18d7-4191-b2f1-801617130991.png)

**Comment by carlhong** [comment]
@1022ranji  It is supported now. You can check crab/pangolin network on Subscan.
