### ISSUE TITLE
 Type mapping for new network.

### ISSUE THREAD

**Issue by sanjay-del** [itering/subscan-essentials#174]
Is there any tool that will generate a type mapping like these `https://github.com/itering/scale.go/tree/master/network` for a new network. 
If I want to run subscan-essentials for a new network the config `https://github.com/itering/subscan-essentials/tree/master/configs/source` file is necessary but I have no way of creating the json file.

**Comment by freehere107** [comment]
If the substrate already supports metadata v14, the custom type is not required. There is currently no tool that can be automatically generated, you can refer to this to https://github.com/itering/subscan-essentials/blob/master/custom_type.md write your own

**Comment by sanjay-del** [comment]
Yeah i got that but in this project the network type mapping has to be explicitly specified in the env file and service.go `https://github.com/itering/subscan-essentials/blob/master/internal/service/service.go#L72` file needs the mapping to run. So is if the network node supports v14 metadata and type mapping is not needed how do i run this code repo without crashing.

**Comment by freehere107** [comment]
You just need to add 1 empty {network}.json

**Comment by sanjay-del** [comment]
thanks
