### ISSUE TITLE
where can I find v2 api?

### ISSUE THREAD

**Issue by MrHunter1986** [itering/subscan-essentials#177]
I setup the subscan successfully but couldn't find  api/v2/scan/search to get balance of a given account

**Comment by freehere107** [comment]
@MrHunter1986  https://docs.api.subscan.io/#v2-api

**Comment by MrHunter1986** [comment]
@freehere107 Thanks.But my problem is I setup subscan locally, and when I use 

curl -X POST --header 'Content-Type: application/json' --data-raw '{"key": "1REAJ1k691g5Eqqg9gL7vvZCBG7FCCZ8zgQkZWd4va5ESih"}' http://127.0.0.1:4399/api/v2/scan/search

The output is "404 page not found"


While the other non-v2 requests seems ok.

**Comment by freehere107** [comment]
@MrHunter1986 Most of the APIs of https://www.subscan.io/ are not in subscan-essentials. At present, this version only provides a simple template, which allows developers to develop secondary development based on existing data.
