### ISSUE TITLE
Price History and Conversion API and UI [Feature Request]

### ISSUE THREAD

**Issue by AlexChien** [itering/subscan-essentials#24]
# Price History and Conversion API and UI [Feature Request]

## Background

At present, Subscan is displaying price info for KSM and DOT. The backend is collecting price info at regular intervals for quite some time.  It's about time to generate price history chart views and provide historical price info through API for external applications.  A feature request was received about fetching historical prices based on the timestamp or block height and a currency converter between token and USD based on a specific time or block height thought API.  Such applications like grant proposal or on-chain proposal applying for treasury funding with requested amount denominated in tokens or USD and vice versa.  

- [x] Develop history price and conversion API
- [x] Develop UI tool to support visualized conversion

API documentation:
- Kusama: [link](https://documenter.getpostman.com/view/1618960/SzYXVdyM?version=latest#1be234e5-e073-4397-aebd-b5ef442cd966)
- Polkadot: [link](https://documenter.getpostman.com/view/1618960/T17Gf7to?version=latest#6966f5e5-119f-4881-8c04-1a9b4e17976f)

UI tool:
- Kusama: [link](https://kusama.subscan.io/tools/price_converter)
- Polkadot: [link](https://polkadot-cc1.subscan.io/tools/price_converter)

### API

Two APIs should be created, general price query and currency conversion.

Examples below are for easy demonstration purposes. Please make necessary changes when implementing and update docs accordingly.

#### /price
Historical price query.

@endpoint: /api/open/price
@method: POST

@param base: Base Currency [KSM|DOT|RING] Those tokens that have meaningful collectible price info.
@param quote: Quote Currency [USD], by default USD.  Right now, we only support USD. This parameter can be omitted for the time being.  But it's kept here for a future extension that API may include quote currency such as BTC, ETH, etc.
@param time: Unix timestamp or block height by checking the integer range for passed-in value.  The blockchain of the block height is determined by the API domain prefix.  If omitted, return the latest price.  Because price info is fetched and stored in DB at intervals, the requested time will hit blank most of the time, in this case, return the latter price of the two price points before and after.  These two price points should be returned as a reference as well to keep it as objective as possible and let the external application decide how to deal with the data.  In order to support query price based on block height, when saving price at a particular time, its corresponding block height should be kept as well, or an internal function exists to facilitate time2height conversion. 

Example: 

    # Check KSM's latest price
    # kusama.subscan.io/api/open/price?base=KSM
    curl -POST -H "Content-Type: application/json" --data '{ "base":KSM}' https://kusama.subscan.io/api/open/price
    
    # Check DOT's USD price at block height 56704
    # polkadot.subscan.io/api/open/price?base=DOT&quote=USD&time=56704
    curl -POST -H "Content-Type: application/json" --data '{ "base":"DOT", "quote":"USD", "time":56704}' polkadot.subscan.io/api/open/price
    
    # response
    {
      "code": 0,
      "message": "Success",
      "generated_at": 1593181254, # Time of API response time stamp
      "data": {
        "price": 117.32,
        "time": 1593175348,
        "height": 56731,
        "generated_at": 1593181254 # Time of API response time stamp
        "records": [
          {
            "price": 112.12,
            "time": 1593173934,
            "height": 56700,
          },
          {
            "price": 117.32,
            "time": 1593175348,
            "height": 56731,
          }
        ] # Price points before and after
      }
    }

#### /currency_converter
Conversion calculator returns the amount of target currency base on the amount of source currency given historical price.

@endpoint: /api/open/currency_converter
@method: POST

@param from: Token to convert [KSM|DOT|RING] Those tokens that have meaningful collectible price info.
@paarm value: Amount of tokens to convert
@param to: Target token [KSM|DOT|RING] Those tokens that have meaningful collectible price info. If same as `from`, always return the same output as `value` value.
@param time: Unix timestamp or block height by checking the integer range for passed-in value.  The blockchain of the block height is determined by the API domain prefix.  If omitted, use the latest price for conversion, otherwise use the price at a specified time or block height for conversion.

Example: 

    # Based on latest price, query 1000KSM=?USD
    kusama.subscan.io/api/open/currency_converter?from=KSM&value=1000&to=USD
    curl -POST -H "Content-Type: application/json" --data '{ "from":"KSM","value":1000,"from":"USD","quote":"DOT"}' https://kusama.subscan.io/api/open/currency_converter
    
    # Based on the pric at block height 56704, query 1000USD=?Dot
    # polkadot.subscan.io/api/open/currency_converter?from=USD&value=1000&to=DOT&time=5670
    curl -POST -H "Content-Type: application/json" --data '{ "time":56704,"value":1000,"from":"USD","quote":"DOT"}' https://polkadot-cc1.subscan.io/api/open/currency_converter
    
    # response
    {
      "code": 0,
      "message": "Success",
      "generated_at": 1593181254, # Time of API response time stamp
      "data": {
        "output": "8.5236958745",  # Follow the price api sample above, DOT/USD: 117.32 @ #56704 
        "price": {
          "price": "117.32",
          "time": 1593175348,
          "height": 56704,
          "records":[
            ...
          ]
        } # price object can use the same object in /price API
      }
    }
        
#### /currencies 
List of currencies that support price query and conversion.

@endpoint: /api/open/currencies
@method: POST

@params: none

Example: 

    # List of currencies that support price query and conversion at Kusama Network
    # kusama.subscan.io/api/open/currencies
    curl -POST -H "Content-Type: application/json" https://kusama.subscan.io/api/open/currencies

    {
      "code": 0,
      "message": "Success",
      "generated_at": 1593181254,
      "data": {
        "currencies": ["KSM/USD", "KSM/BTC"]
      }
    }

    # List of currencies that support price query and conversion at Darwinia Network
    # darwinia.subscan.io/api/open/currencies
    curl -POST -H "Content-Type: application/json" https://darwinia.subscan.io/api/open/currencies

    {
      "code": 0,
      "message": "Success",
      "generated_at": 1593181254, 
      "data": {
        "currencies": ["RING/USD", "KTON/USD"]
      }
    }
    
### UI Conversion UI tool

A UI tool to support currency conversion based on API service.

- Select `From Currency` and input `Amount`
- Input time of price using `Datetime` picker or block height number
- Select `To Currency`
- Display `Amount`

**Comment by AlexChien** [comment]
Please update API documentation as well at https://documenter.getpostman.com/view/1618960/SzYXVdyM?version=latest when done.

**Comment by freehere107** [comment]
Kusama still in progress, Polkadot work has done

**Comment by freehere107** [comment]
Kusama history price has done
