### ISSUE TITLE
Add the ability to share a link for the historic price converter tool 

### ISSUE THREAD

**Issue by rrtti** [itering/subscan-essentials#32]
It would be useful to have the ability to share a link such as https://kusama.subscan.io/tools/price_converter?from=USD&to=KSM&value=1000&block=1234, that allows to include the information in proposal/tips by the Author.

So instead of having to explain why one requests XXX.XX KSM, the link above can be provided this and it would contain all the relevant information. 

The link should answer to:
- what was the amount in USD (or others... as supported);
- what was the conversion date;
- what was the rate.
- If I request a price at 17:23hs, the code will likely call only the price info from 17:21 or 17:28. It would be nice to return this date/time that has been used as proof that there was no mistake.

**Comment by AlexChien** [comment]
ref #24

**Comment by AlexChien** [comment]
Add timestamp for the price used should be fine, something like below:
![截屏2020-07-08 下午3 52 43](https://user-images.githubusercontent.com/41967/86892659-20712400-c133-11ea-8f53-1cea9dae26f3.png)

**Comment by AlexChien** [comment]
功能是有了，下面可以让yuqi改进一下设计了。目前视觉上的问题是上面的表单比较规整，下面的结果只是一些简单文字，头重脚轻虎头蛇尾的感觉。

需要突出的是最终输出的数量，这是用户需要的信息。基于的价格和时间是次要信息，表现上要有区别。
