### ISSUE TITLE
Service can run, but it show timeout in log

### ISSUE THREAD

**Issue by garysdevil** [itering/subscan-essentials#33]
docker-compose
![图片](https://user-images.githubusercontent.com/41293784/87004345-da2dca80-c1ef-11ea-901d-c3503da10f1c.png)
mysql:
![图片](https://user-images.githubusercontent.com/41293784/87004490-15c89480-c1f0-11ea-96a6-2803b30d7fe4.png)
logs:
![图片](https://user-images.githubusercontent.com/41293784/87004285-c5e9cd80-c1ef-11ea-83de-f477a7945d52.png)
I think there something wrong, it show timeout in log, but I dont know why.
And my polkadot run well as westend network.

**Comment by freehere107** [comment]
Try exec``Subscan daemon`` and debug by ``tail -f ../log/substrate_log ``

**Comment by garysdevil** [comment]
> tail -f ../log/substrate_log

![图片](https://user-images.githubusercontent.com/41293784/87041657-25ae9b80-c225-11ea-8e6e-78bdd1408ff8.png)

**Comment by freehere107** [comment]
@garysdevil code seems to be outdated, please try to upgrade the latest version

**Comment by garysdevil** [comment]
> 
> 
> @garysdevil code seems to be outdated, please try to upgrade the latest version

I cloned it from master branch yesterday, I think it is the newest

**Comment by freehere107** [comment]
> > @garysdevil code seems to be outdated, please try to upgrade the latest version
> 
> I cloned it from master branch yesterday, I think it is the newest

OK，i find out this bug

**Comment by freehere107** [comment]
Fix https://github.com/itering/subscan-essentials/pull/40, I del subscription id field, This field currently has no use

**Comment by freehere107** [comment]
Fix https://github.com/itering/subscan-essentials/pull/40, I del subscription id field, This field currently has no use

**Comment by garysdevil** [comment]
> 
> 
> Fix #40, I del subscription id field, This field currently has no use

One service can not start in docker when I upgrade the latest version at 11th in July
All can run well when I update the Dockerfile.
![图片](https://user-images.githubusercontent.com/41293784/87635860-5422fe00-c772-11ea-81ae-6feecb2cb4a5.png)
