### ISSUE TITLE
why use daemon to start the service

### ISSUE THREAD

**Issue by ianhe8x** [itering/subscan-essentials#36]
I suppose there must be some reasons that daemon is used, though it is inconvenient for me for several reasons.
1. for production deployment, usually we intent to deploy it in a container, which requires the app running in the foreground.
2. for local development, with the daemon setup, it is really hard to debug the app.

**Comment by wi1dcard** [comment]
Having the same question.

**Comment by freehere107** [comment]
@ianhe8x daemon for blockchain data fetch, API container for subscan data query.
for local development, you can use ``go run main.go start substrate `` for debug

**Comment by freehere107** [comment]
@ianhe8x The API service of subscan will have a lot of visits, which are basically read operations. During the running process, multiple pods (k8s) will be started, but the daemon only needs one to write blockchain data.
