### ISSUE TITLE
the make and other instructions in README.md aren't working.

### ISSUE THREAD

**Issue by nblogist** [itering/subscan-essentials#41]
I am cloning the repo and then following the instructions on the readme file but it doesn't even have a make file, probably I am doing something wrong, if so it'll be awesome if someone can help me with the steps to setting up a running subscan repo on my localhost.

Thanks in adv!

**Comment by freehere107** [comment]
Hello, some changes have been made recently and have not been updated to the readme. Has been updated, thank you for pointing out the error.

**Comment by nblogist** [comment]
@freehere107  Thanks for changing it, now I am able to make a build, but upon running ./cmd/subscan --conf configs --install I get the following error 
```
panic: plugin.Open("configs/plugins/balance"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader

goroutine 1 [running]:
github.com/itering/subscan/plugins.registerStatic()
        /home/furqan/reference_projects/subscan-essentials/plugins/registry.go:58 +0x71c
github.com/itering/subscan/plugins.init.0()
        /home/furqan/reference_projects/subscan-essentials/plugins/registry.go:16 +0x7a
```
go version go1.14.4 linux/amd64

I have made the latest pulls from the master branch, aren't plugins working on different versions?

**Comment by nblogist** [comment]
@freehere107  Also I think it meant ```docker-compose``` instead of  ```docker-composer``` in the READEME?

Here:

```
docker-composer build

docker-composer up -d
```

**Comment by nblogist** [comment]
Also while running docker instructions after running ```docker-compose up -d``` the following error shows up, I think it'll be great if a command for this could be added (if this issue isn't with me only).
Thanks in advance!

**Comment by nblogist** [comment]
Running through the docker image leads to almost the same error. After running ```sudo docker run scan/backend``` the following error generates: any help solving this would be awesome!

```
panic: open /plugins: no such file or directory

goroutine 1 [running]:
github.com/itering/subscan/plugins.registerStatic()
        /subscan/plugins/registry.go:53 +0x739
github.com/itering/subscan/plugins.init.0()
        /subscan/plugins/registry.go:16 +0x7b

```

**Comment by nblogist** [comment]
Running ```python run.py``` in the cmd directory renders this, please direct me if I am doing something wrong:

```
sh: 1: ./subscan: not found
('start to listen daemon status :', '2020-07-15 05:21:32')

```

**Comment by freehere107** [comment]
> @freehere107 Thanks for changing it, now I am able to make a build, but upon running ./cmd/subscan --conf configs --install I get the following error
> 
> ```
> panic: plugin.Open("configs/plugins/balance"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader
> 
> goroutine 1 [running]:
> github.com/itering/subscan/plugins.registerStatic()
>         /home/USERNAME/projects/subscan-essentials/plugins/registry.go:58 +0x71c
> github.com/itering/subscan/plugins.init.0()
>         /home/USERNAME/projects/subscan-essentials/plugins/registry.go:16 +0x7a
> ```
> 
> go version go1.14.4 linux/amd64
> 
> I have made the latest pulls from the master branch, aren't plugins working on different versions?
> 
> P.S. Same output for `./cmd/subscan --conf configs`

**Comment by freehere107** [comment]
@nblogist thank you reply, subscan-essentials still under development, there will be many potential problems here, I will fix it one by one

**Comment by freehere107** [comment]
> @freehere107 Thanks for changing it, now I am able to make a build, but upon running ./cmd/subscan --conf configs --install I get the following error
> 
> ```
> panic: plugin.Open("configs/plugins/balance"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader
> 
> goroutine 1 [running]:
> github.com/itering/subscan/plugins.registerStatic()
>         /home/USERNAME/projects/subscan-essentials/plugins/registry.go:58 +0x71c
> github.com/itering/subscan/plugins.init.0()
>         /home/USERNAME/projects/subscan-essentials/plugins/registry.go:16 +0x7a
> ```
> 
> go version go1.14.4 linux/amd64
> 
> I have made the latest pulls from the master branch, aren't plugins working on different versions?
> 
> P.S. Same output for `./cmd/subscan --conf configs`

yes, go plugin not working on different versions, please rebuild it

**Comment by nblogist** [comment]
@freehere107  I understand, thank you for taking out the time to do so!

**Comment by nblogist** [comment]
> > @freehere107 Thanks for changing it, now I am able to make a build, but upon running ./cmd/subscan --conf configs --install I get the following error
> > ```
> > panic: plugin.Open("configs/plugins/balance"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader
> > 
> > goroutine 1 [running]:
> > github.com/itering/subscan/plugins.registerStatic()
> >         /home/USERNAME/projects/subscan-essentials/plugins/registry.go:58 +0x71c
> > github.com/itering/subscan/plugins.init.0()
> >         /home/USERNAME/projects/subscan-essentials/plugins/registry.go:16 +0x7a
> > ```
> > 
> > 
> > go version go1.14.4 linux/amd64
> > I have made the latest pulls from the master branch, aren't plugins working on different versions?
> > P.S. Same output for `./cmd/subscan --conf configs`
> 
> yes, go plugin not working on different versions, please rebuild it

Hey @freehere107, I made a rebuild its still the same, can you probably tell me what version the plugin is built on and I can roll back to that  version probably, to solve the issue?

**Comment by freehere107** [comment]
@nblogist, You can delete all the plugins in configs/plugins, there are indeed some problems here, I am also doing some experiments on plugins, the current solution is not particularly ideal
