### ISSUE TITLE
why not provide transfer , search api

### ISSUE THREAD

**Issue by kongying** [itering/subscan-essentials#42]
why not provide transfer , search api

**Comment by freehere107** [comment]
@kongying, subscan-essentials did not  provide transfer, search API,  these features are the version of subscan.io

**Comment by kongying** [comment]
Is there a limit to using subscan.io‘s api

**Comment by kongying** [comment]
@freehere107 Is there a limit to using subscan.io‘s api

**Comment by freehere107** [comment]
> @freehere107 Is there a limit to using subscan.io‘s api

No restrictions, can be used directly
