### ISSUE TITLE
[Bug] Some events are not passed to plugin.ProcessEvent()

### ISSUE THREAD

**Issue by ianhe8x** [itering/subscan-essentials#46]
*Service.afterEvent is invoked in a go routine, where `event` is a pointer. This leads to a problem because in a for-loop, that `event` variable will be mutated to next value in the loop.

https://github.com/itering/subscan-essentials/blob/89a3c12817be413092012db2d3e6f086c72d5569/internal/service/event.go#L33

**Comment by freehere107** [comment]
Please solve conflict first
