### ISSUE TITLE
[BUG] api/scan/extrinsic:query extrinsic_hash is null,but extrinsic_index is ok.

### ISSUE THREAD

**Issue by tinshen** [itering/subscan-essentials#55]
curl -H "Content-Type: application/json" -X POST -d '{"hash":"0xf037b127a5c0ab9cf73e9b907a1d41f02789b33d3a6d622f615abddf643e3588"}' http://127.0.0.1:4399/api/scan/extrinsic
**reponse** 
{"code":0,"message":"Success","ttl":1,"data":null}

===========
curl -H "Content-Type: application/json" -X POST -d '{"extrinsic_index":"1270914-3"}' http://127.0.0.1:4399/api/scan/extrinsic
**reponse** 
{"code":0,"message":"Success","ttl":1,"data":{"block_timestamp":1598164302,"block_num":1270914,"extrinsic_index":"1270914-3","call_module_function":"transfer","call_module":"balances","account_id":"12zaAbcdGQXqRnJLzXPEicaexuNgrguUKRSrXsavbupHaJwK","signature":"3a8007a409fe44e952205ed8c269d57e26a374fc637b03186e06e9ac8e409311e7d827c5fb00eae0009e1bb4936a324a6fc1e240dff43cb9ad9196c73847978e","nonce":0,"extrinsic_hash":"0xf037b127a5c0ab9cf73e9b907a1d41f02789b33d3a6d622f615abddf643e3588","success":true,"params":[{"name":"dest","type":"Address","value":"56daf75bd0f09c11d798263bc79baeb77c4b4af1dbd372bbe532b1f8702b2a7e","valueRaw":""},{"name":"value","type":"Compact\u003cBalance\u003e","value":"14999835000000","valueRaw":""}],"event":[],"fee":"155000000","finalized":false}}

**Comment by freehere107** [comment]
https:// crab.demo.subscan.io It is the demo server deployed by the current version of the code


```bash
curl -H "Content-Type: application/json" -X POST -d '{"hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db"}' https://crab.demo.subscan.io/api/scan/extrinsic
```
> response
{"code":0,"message":"Success","ttl":1,"data":{"block_timestamp":1593174756,"block_num":679872,"extrinsic_index":"679872-2","call_module_function":"bond_extra","call_module":"staking","account_id":"5CJCRABfEW13u547Yw4SdNpRTWYyjaGLD9ZPJrR4GzUce8ya","signature":"3692e5cb5d72ce75b20a37565ca09a8f474248a976cd667dde9f4c91c0bc0aa800a47b2aa20f0183790a834d8fc0dba212d5a56b14b9423d905469c8b5e74904","nonce":2,"extrinsic_hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db","success":false,"params":[{"name":"max_additional","type":"StakingBalanceT","value":{"RingBalance":"4400000000000"},"valueRaw":""},{"name":"promise_month","type":"u8","value":0,"valueRaw":""}],"event":[{"event_index":"679872-2","block_num":679872,"extrinsic_idx":2,"module_id":"staking","event_id":"BondRing","params":"[{\"type\":\"RingBalance\",\"value\":\"4400000000000\",\"value_raw\":\"\"},{\"type\":\"TsInMs\",\"value\":1593174756003,\"value_raw\":\"\"},{\"type\":\"TsInMs\",\"value\":1593174756003,\"value_raw\":\"\"}]","extrinsic_hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db","event_idx":2},{"event_index":"679872-2","block_num":679872,"extrinsic_idx":2,"module_id":"treasury","event_id":"DepositRing","params":"[{\"type\":\"RingBalance\",\"value\":\"80000000\",\"value_raw\":\"\"}]","extrinsic_hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db","event_idx":3},{"event_index":"679872-2","block_num":679872,"extrinsic_idx":2,"module_id":"balances","event_id":"Deposit","params":"[{\"type\":\"AccountId\",\"value\":\"8a9673ef43c3f41d8b772fd89a5d9abfa21afa4d9ecdeff1d182beb1b8e76b14\",\"value_raw\":\"\"},{\"type\":\"Balance\",\"value\":\"20000000\",\"value_raw\":\"\"}]","extrinsic_hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db","event_idx":4},{"event_index":"679872-2","block_num":679872,"extrinsic_idx":2,"module_id":"system","event_id":"ExtrinsicSuccess","params":"[{\"type\":\"DispatchInfo\",\"value\":{\"class\":\"Normal\",\"paysFee\":false,\"weight\":355000000},\"value_raw\":\"\"}]","extrinsic_hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db","event_idx":5}],"fee":"0","finalized":true}}

Please check whether the corresponding hash is correct

**Comment by tinshen** [comment]
I.m modify env.go for polkadot to sync block to mysql. 

I compared local's data with polkadot.subscan.io.

the lcoal data is lost.

**Comment by freehere107** [comment]
@tinshen You mean your data is lost,  you can check you console SQL query

**Comment by tinshen** [comment]
使用/api/scan/extrinsic接口
如果使用{"extrinsic_index":"1285217-2"}能查询到数据.
如果使用{"hash":"0x2aa4dfa74208b55ebfc2ee87c9f0a82fc1a329d9623056f1864ecee31316f9a7"} 查询不到。
sql 日志
INSERT INTO `chain_extrinsics_1` (`extrinsic_index`,`block_num`,`block_timestamp`,`extrinsic_length`,`version_info`,`call_code`,`call_module_function`,`call_module`,`params`,`account_id`,`signature`,`nonce`,`era`,`extrinsic_hash`,`is_signed`,`success`,`fee`) VALUES ('1285217-2',1285217,1598250240,'','84','0500','transfer','balances','[{"name":"dest","type":"Address","value":"56daf75bd0f09c11d798263bc79baeb77c4b4af1dbd372bbe532b1f8702b2a7e","value_raw":""},{"name":"value","type":"Compact\u003cBalance\u003e","value":"18836000000","value_raw":""}]','c2b4ba892a70f68e4490c02f5499fb2c90e5cd394e0c97818d1ab9567adb033d','5e0ceaecebcffd8f9bbf7a05974b774c29307d985ffa12501469a50c71d6f23cfec71f64500c43a74804ba2e00dc9ac72d4bec71bc8ac744441b6c460e6c3a8d',0,'d501','0x2aa4dfa74208b55ebfc2ee87c9f0a82fc1a329d9623056f1864ecee31316f9a7',true,true,'154000000') 


同样的使用/api/scan/block
通过{"block_num":"1285217"}查询到
通过{"block_hash":"0xfd01df54354bab6e6c9df5e42fe6909945784a1cdfdc92b7aef45a460aa0fdc9"}不行。
数据库里面有数据查询相关的sql
 INSERT INTO `chain_blocks` (`block_num`,`block_timestamp`,`hash`,`parent_hash`,`state_root`,`extrinsics_root`,`logs`,`extrinsics`,`event_count`,`extrinsics_count`,`event`,`spec_version`,`validator`,`codec_error`,`finalized`) VALUES (1285217,1598250240,'0xfd01df54354bab6e6c9df5e42fe6909945784a1cdfdc92b7aef45a460aa0fdc9','0xc0b971be48655eadcddf9d007e0c0c2e284f77ed3ce8f0d9708c6d664058f770','0xd60b8e945f8422b3c8db538a7c1976d0a5297b19577f912c6e14ea70e309c63d','0xe9e6e1cd0c4ae9c263b8066b5c5b118592640088204d5d7fd245c6efbdc954c0','["0x0642414245b501031a000000808fe00f000000003a99ae84a0132f15f1c0c7a722aa2b046a1fea85634abb166746498fa2e5150472e02db6deec2ed57da1eb67920ff27f0d5e15e832c6ba6a8f8164b1081c890404628fd082fde6c9389ef55d904f7642f1a8856ed09f19d203d64dad7d483f0e","0x054241424501018cd48f4a281c38b26cfe743c4b863fa7b8f6c29495fc27e86a8c0110ae25517a64a948089974fa96b2945c5934b466cd22fd5df9a8e6dc9dd02290c948ed3f89"]','["0x280403000b0048231f7401","0x1004140000","0x390284c2b4ba892a70f68e4490c02f5499fb2c90e5cd394e0c97818d1ab9567adb033d015e0ceaecebcffd8f9bbf7a05974b774c29307d985ffa12501469a50c71d6f23cfec71f64500c43a74804ba2e00dc9ac72d4bec71bc8ac744441b6c460e6c3a8dd5010000050056daf75bd0f09c11d798263bc79baeb77c4b4af1dbd372bbe532b1f8702b2a7e07008db66204"]',0,3,'',18,'1650c532ed1a8641e8922aa24ade0ff411d03edd9ed1c6b7fe42f1a801cee37c',false,true)

**Comment by freehere107** [comment]
@tinshen  Fixed, thank you reply
