### ISSUE TITLE
sync chain_event is null.

### ISSUE THREAD

**Issue by tinshen** [itering/subscan-essentials#59]
in this rpc
/api/scan/extrinsic、/api/scan/block
The event field is empty in the respone.

[2020-08-25 18:59:05]  [0.33ms]  SELECT * FROM `chain_events_1`  WHERE (event_index = '1285217-2')  
[0 rows affected or returned ]

**Comment by freehere107** [comment]
```
curl -H "Content-Type: application/json" -X POST -d '{"hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db"}' https://crab.demo.subscan.io/api/scan/extrinsic
```
```
curl -H "Content-Type: application/json" -X POST -d '{"block_num":1568959}' https://crab.demo.subscan.io/api/scan/block
```

I tried it and there were no problems

**Comment by tinshen** [comment]
> @tinshen
> 
> ```
> curl -H "Content-Type: application/json" -X POST -d '{"hash":"0x65fd6ca2815ae867b870d2e2e026f2b9b35f25b15a70c15409b9b5ad9f4896db"}' https://crab.demo.subscan.io/api/scan/extrinsic
> ```
> 
> ```
> curl -H "Content-Type: application/json" -X POST -d '{"block_num":1568959}' https://crab.demo.subscan.io/api/scan/block
> ```
> 
> I tried it and there were no problems

SendWsRequest with commad  state_getStorageAt had blank response  from polkadot node.

**Comment by freehere107** [comment]
@tinshen Maybe polkadot node is not archive
