### ISSUE TITLE
this code respone is diff with polkadot.subscan.io

### ISSUE THREAD

**Issue by tinshen** [itering/subscan-essentials#60]
api/scan/extrinsic

for exp:
lost field: account_display、error、lifetime。

the success field has diff result.

0xf2082f630332982494cad241a29d6e7744a381c64424b6f0ad295b208ea48377

the website is false,but the github code is true.

**Comment by freehere107** [comment]
@tinshen https://github.com/itering/subscan-essentials only subscan essentials,  There are many features of subscan.io that are not available

**Comment by tinshen** [comment]
> @tinshen https://github.com/itering/subscan-essentials only subscan essentials, There are many features of subscan.io that are not available

If so, it is recommended to write it clearly in readme, and it is not recommended to use it in production environment.
Otherwise, there will be abnormal transfer, which is considered normal transaction.
It's too dangerous.

**Comment by freehere107** [comment]
> > @tinshen https://github.com/itering/subscan-essentials only subscan essentials, There are many features of subscan.io that are not available
> 
> If so, it is recommended to write it clearly in readme, and it is not recommended to use it in production environment.
> Otherwise, there will be abnormal transfer, which is considered normal transaction.
> It's too dangerous.

This is not directly usable in the production environment, this is just a basic framework of subscan, and some other content needs to be developed

**Comment by tinshen** [comment]
> > > @tinshen https://github.com/itering/subscan-essentials only subscan essentials, There are many features of subscan.io that are not available
> > 
> > 
> > If so, it is recommended to write it clearly in readme, and it is not recommended to use it in production environment.
> > Otherwise, there will be abnormal transfer, which is considered normal transaction.
> > It's too dangerous.
> 
> This is not directly usable in the production environment, this is just a basic framework of subscan, and some other content needs to be developed

that'is bad news.
