### ISSUE TITLE
identity.provideJudgement extrinsic is not recognised

### ISSUE THREAD

**Issue by TheGoldenEye** [itering/subscan-essentials#61]
the judgement is not shown for different accounts
e.g. https://polkadot.subscan.io/account/14K71ECxvekU8BXGJmSQLed2XssM3HdBYQBuDUwHeUMUgBHk

It seems, that a `identity.provideJudgement` extrinsic is not recognised, if sent through a proxy
e.g. https://polkadot.subscan.io/extrinsic/1286861-2

**Comment by freehere107** [comment]
@TheGoldenEye Thank you for the information, I will fix this as soon as possible

**Comment by freehere107** [comment]
@TheGoldenEye It has been fixed, please check your account page to see if it is displayed normally.
