### ISSUE TITLE
Data not synchronized

### ISSUE THREAD

**Issue by wo4zhuzi** [itering/subscan-essentials#63]
I have been running the program for two hours. The data table in MySQL is empty. How to solve it.

terminal：

```
(/root/subscan-essentials/internal/dao/runtimeVersion.go:32)
[2020-09-02 08:53:40]  [0.32ms]  SELECT spec_version,raw_data FROM `runtime_versions`   ORDER BY spec_version DESC,`runtime_versions`.`id` ASC LIMIT 1
[0 rows affected or returned ]

INFO 09/02-08:53:42.594 /root/go/pkg/mod/github.com/go-kratos/kratos@v0.5.0/pkg/net/http/blademaster/server.go:97 blademaster: start http listen addr: [::]:4399
```

mysql :

![image](https://user-images.githubusercontent.com/20334885/91969413-a501ac80-ed48-11ea-9b2e-265bda74f1eb.png)

@freehere107

**Comment by freehere107** [comment]
@wo4zhuzi hi, Please check if the WebSocket connection is normal

**Comment by wo4zhuzi** [comment]
> @wo4zhuzi hi, Please check if the WebSocket connection is normal


The websocket link is normal. It has opened port 4399, but the data is not synchronized.

Because I will report an error when I turn off the node:

"no such host Dial: will try again in 2.270204124s seconds"

Or what additional parameters should I add to the startup node?

**Comment by freehere107** [comment]
Since  haven't received a reply for a long time, I will close it, if there is a problem, please reopen it
