### ISSUE TITLE
I don't know why, is there anyone  help me?

### ISSUE THREAD

**Issue by jacklcz** [itering/subscan-essentials#66]
https://github.com/itering/subscan-essentials/blob/b7633f33edf0004579e46f967b2eea49e4293056/internal/service/extrinsic.go#L114

**Comment by freehere107** [comment]
@jacklcz Every extrinsic corresponds one **system** event , system event will display this extrinsic success or fail

**Comment by jacklcz** [comment]
> @jacklcz Every extrinsic corresponds one **system** event , system event will display this extrinsic success or fail

这个函数是不是有问题？？我现在数据库里的这个结果，是乱套的，链上是失败的，但是chain_extrinsic表中的success都是1。

func (s *Service) getExtrinsicSuccess(e []model.ChainEvent) bool {
	for _, event := range e {
		if strings.EqualFold(event.ModuleId, "system") {
			return strings.EqualFold(event.EventId, "ExtrinsicFailed")
		}
	}
	return true
}

**Comment by jacklcz** [comment]
能加个微信吗？我的微信：wendy19891102

**Comment by jacklcz** [comment]
> > @jacklcz Every extrinsic corresponds one **system** event , system event will display this extrinsic success or fail
> 
> 这个函数是不是有问题？？我现在数据库里的这个结果，是乱套的，链上是失败的，但是chain_extrinsic表中的success都是1。
> 
> func (s *Service) getExtrinsicSuccess(e []model.ChainEvent) bool {
> for _, event := range e {
> if strings.EqualFold(event.ModuleId, "system") {
> return strings.EqualFold(event.EventId, "ExtrinsicFailed")
> }
> }
> return true
> }

能加个微信吗？我的微信：wendy19891102

**Comment by freehere107** [comment]
@jacklcz 你可以在数据库看下对应Extrinsic 的event

**Comment by freehere107** [comment]
Since haven't received a reply for a long time, I will close it, if there is a problem, please reopen it
