### ISSUE TITLE
Request failed with status code 405?

### ISSUE THREAD

**Issue by zhangtianai** [itering/subscan-essentials#68]

**Comment by freehere107** [comment]
@zhangtianai Could you describe the problem in detail

**Comment by freehere107** [comment]
Since haven't received a reply for a long time, I will close it, if there is a problem, please reopen it

**Comment by Raytlty** [comment]
@freehere107 Hello, I meet the same errors. Can you help me fix this.
![image](https://user-images.githubusercontent.com/11255510/115989207-e4d71600-a5ef-11eb-8614-3e75f3d2cda9.png)

**Comment by freehere107** [comment]
> @freehere107 Hello, I meet the same errors. Can you help me fix this.
> 
> ![image](https://user-images.githubusercontent.com/11255510/115989207-e4d71600-a5ef-11eb-8614-3e75f3d2cda9.png)
> 
> 

Please send me some backend log
