### ISSUE TITLE
Can't access Subscan on Firefox

### ISSUE THREAD

**Issue by Tbaut** [itering/subscan-essentials#69]
It's showing the following on firefox (fine on chrome) when accessing https://www.subscan.io/

```
Secure Connection Failed

An error occurred during a connection to kusama.subscan.io. The OCSP response does not include a status for the certificate being verified.

Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by wi1dcard** [comment]
Hi @Tbaut , thank you for reporting this!

TLDR: This issue was caused by a bug in our load balancer. We've hot fixed it and it should not be a problem again at least within 2 months.

For more detailed information, if you're interested in, please refer to kubernetes/ingress-nginx#6198.
