### ISSUE TITLE
Document Site

### ISSUE THREAD

**Issue by clearloop** [itering/subscan-essentials#8]
Serve docs at `/docs`, list the APIs, if there is any `swagger.yml` would be better.

**Comment by clearloop** [comment]
`swagger.yml` could be generated in one command after #11

**Comment by nblogist** [comment]
@clearloop I am trying to use events used in [this](https://edgeware.subscan.io/event?module=Staking&event=Slash) page on subscan, It'll be awesome if you can guide on using the APIs here, I had a look at the API [doc](https://github.com/itering/subscan-essentials/blob/master/docs/index.md) but I am not sure what URL to hit the request on it. Thanks!

**Comment by nblogist** [comment]
For anyone trying:
Make a POST request to `https://edgeware.subscan.io*INSERT API PATH HERE*` e.g. /api/scan/block with a parameter of let's say
```
{
	"block_num" : 2113700
}
```

**Comment by freehere107** [comment]
@nblogist Hi, at present, most of the APIs of subscan.io related websites are different from subscan-essentials. The API doc of subscan.io is private

**Comment by nblogist** [comment]
@freehere107 I see, so Subscan and subscan-essentials are two different things?
Isn't subsan.io open source? 
Also what's the way to run subscan-essentials? ( Like do I have to run the node along side? Also where did the subscan-ui comes in the equation )?

Thank you for taking out the time to answer questions!
