### ISSUE TITLE
edgeware.subscan.io is showing incorrect total balances

### ISSUE THREAD

**Issue by nblogist** [itering/subscan-essentials#82]
The total incoming transfers are less than the total balance:

![image](https://user-images.githubusercontent.com/35498810/97758351-82a9c680-1b20-11eb-82b2-d5c4b1adc683.png)
This is definitely not the balance that totals when adding few incoming transactions. Also its not possible too have this much EDG when the total circulating supply right now is : **5,101,681,270 EDG**

**Comment by freehere107** [comment]
@nblogist fix, thank you
