### ISSUE TITLE
Missing Polkadot Extrinsic (0x4457...47f3a226) on Subscan

### ISSUE THREAD

**Issue by kareemgrant** [itering/subscan-essentials#83]
The following Polkadot extrinsic is currently missing on Subscan.io: `0x4457c25b6812e9262eeab142f77abeb2411b1e3192c930a47f3a226deebcb226`

* [expected subscan url for 0x4457c25b6812e9262eeab142f77abeb2411b1e3192c930a47f3a226deebcb226 extrinsic (not found)](https://polkadot.subscan.io/extrinsic/0x4457c25b6812e9262eeab142f77abeb2411b1e3192c930a47f3a226deebcb226)

However, the same extrinsic is present on Polkascan

* [polkascan url for 0x4457c25b6812e9262eeab142f77abeb2411b1e3192c930a47f3a226deebcb226 extrinsic](https://polkascan.io/polkadot/transaction/0x4457c25b6812e9262eeab142f77abeb2411b1e3192c930a47f3a226deebcb226)

**Comment by freehere107** [comment]
There are some bugs here, thank you for your feedback

**Comment by freehere107** [comment]
@kareemgrant It has been fixed, if there is any problem, please feedback in time.

**Comment by kareemgrant** [comment]
> @kareemgrant It has been fixed, if there is any problem, please feedback in time.

@freehere107 thanks!
