### ISSUE TITLE
Edgeware new transfers didn't show

### ISSUE THREAD

**Issue by Ljzn** [itering/subscan-essentials#84]
The latest transfers of edgeware were happened in 25 days ago on https://edgeware.subscan.io/transfer . But I did receive some EDG with polkadot.js wallet yesterday. What happened?

**Comment by freehere107** [comment]
The reason is because the edgeware network has not been finalized for a long time

**Comment by Ljzn** [comment]
Thanks for the quick reply! So it is a problem of edgeware network, not subscan, right?

**Comment by freehere107** [comment]
> Thanks for the quick reply! So it is a problem of edgeware network, not subscan, right?

yeah，unfinalized block will cause much chaos，so transfer list only display finalized data
