### ISSUE TITLE
Old block not shown as finalized in subscan explorer

### ISSUE THREAD

**Issue by jun0tpyrc** [itering/subscan-essentials#85]
In detail page

https://polkadot.subscan.io/extrinsic/0x2cc489ee273125d3efae9ea8246a6d3057c139412eae7dca3ddf31b9def62985
https://polkadot.subscan.io/block/2407269?tab=comment

while blocks more recent than it all finalized

**Comment by freehere107** [comment]
@jun0tpyrc It probably caches not update, thank you for feedback
