### ISSUE TITLE
Check in configs/source/kusama.json

### ISSUE THREAD

**Issue by jun0tpyrc** [itering/subscan-essentials#89]
@freehere107 
May I confirm if the file in 
https://github.com/itering/subscan-essentials/issues/79#issuecomment-722116255
is still correct & updated to check in to this repo? 🙇‍♂️ thanks

**Comment by freehere107** [comment]
@jun0tpyrc Hey, I update the latest Kusama type.json https://github.com/itering/subscan-essentials/blob/master/configs/source/kusama.json
