### ISSUE TITLE
Disparity with other explorers -- potential fork issue. 

### ISSUE THREAD

**Issue by kianenigma** [itering/subscan-essentials#90]
https://kusama.subscan.io/extrinsic/5401320-1

The staking solution is stored here on subscan (in block 5401320).

https://polkascan.io/kusama/inherent?module=staking&call=submit_election_solution_unsigned&page=1

But it's not in polkascan

https://polkadot.js.org/apps/#/explorer/query/0xfce1a16801d62ac2f35e8e117628846aa9f9936ce103f67d4e4ce6fcc4522c5e

Nor the polkadot js apps explorer. 

When looking for block 5401320 on these explorers, they all have same block hash, so it seems as though this isn't the result of a fork. But the staking solution tx is only listed in subscan

cc @wpank

**Comment by freehere107** [comment]
@kianenigma hey, Thanks for the feedback, this seems a bug, I will fix him as soon as possible

**Comment by kianenigma** [comment]
I am very curious also to know what the bug is and what are you doing wrong that caused this wrong transaction to be recorded. Could also help us debug some related matters.

**Comment by freehere107** [comment]
> I am very curious also to know what the bug is and what are you doing wrong that caused this wrong transaction to be recorded. Could also help us debug some related matters.

@kianenigma This is because subscan will store the new header block, there will be some unfinalized data, but because of the db problem, the unfinalized extrinsic has not been deleted, resulting in the staking solution is stored

**Comment by freehere107** [comment]
@kianenigma hey, this issue has been fixed. If there is any problem, please give feedback in time. Thank you
