### ISSUE TITLE
run config 

### ISSUE THREAD

**Issue by zyjblockchain** [itering/subscan-essentials#92]
I want to run polkadot and kusama , where have env config. thanks
![image](https://user-images.githubusercontent.com/40423181/104168790-8ec3d580-5439-11eb-9dfa-d00e39c6c0b8.png)

**Comment by zyjblockchain** [comment]
do you give me some cases 。 thanks

**Comment by freehere107** [comment]
some to https://github.com/itering/subscan-essentials/issues/93
