### ISSUE TITLE
polkadot 同步链上数据环境变量配置问题

### ISSUE THREAD

**Issue by zyjblockchain** [itering/subscan-essentials#93]
hello, 我想使用一下这个程序来同步polkadot 链上的数据到本地的mysql 中，但是其中有一些环境变量我不是很理解
`EventStorageKey           = GetEnv("SUBSTRATE_EVENT_KEY", "0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7")
	AddressType               = GetEnv("SUBSTRATE_ADDRESS_TYPE", "0")
	BalanceAccuracy           = GetEnv("SUBSTRATE_ACCURACY", "9")
	CommissionAccuracy        = GetEnv("COMMISSION_ACCURACY", "9")
	NetworkNode               = GetEnv("NETWORK_NODE", "polkadot")
	IsProduction              = os.Getenv("DEPLOY_ENV") == "prod"`
	
	这个几个环境变量配置能不能注释一下是主要是什么功能，或者能不能提供一下mainnet 的配置信息。非常感谢。

**Comment by freehere107** [comment]
你只需要设置 NetworkNode = "polkadot" 还有 CHAIN_WS_ENDPOINT= "wss://rpc.polkadot.io/" 就可以了

**Comment by zyjblockchain** [comment]
谢谢你：
EventStorageKey = GetEnv("SUBSTRATE_EVENT_KEY", "0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7")
请问这个变量在kusama 和 polkadot 中都是默认的吗

**Comment by freehere107** [comment]
> 谢谢你：
> EventStorageKey = GetEnv("SUBSTRATE_EVENT_KEY", "0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7")
> 请问这个变量在kusama 和 polkadot 中都是默认的吗

是的

**Comment by zyjblockchain** [comment]
hello，我刚刚通过`./subscan start substrate` 这个命令同步了一下polkadot mainnet 上的数据。有两个疑惑：
1. 我看日志中打印出了很多 error，这个 error 是重复插入相同的block hash 的错误；如下：
![image](https://user-images.githubusercontent.com/40423181/104267084-e579ef80-54cb-11eb-9d7a-7e6f23923928.png)

2. 我看数据库中的chain_block table 中的数据 block_num 列并不是按照区块高度的顺序进行插入的； 如下：
![image](https://user-images.githubusercontent.com/40423181/104267211-27a33100-54cc-11eb-9f2f-8ceeb65dff56.png)

3. 数据库是采用了分表的模式，我刚启动同步之后数据库就自动给建立了第二张表，我看到代码中是每10000行记录进行一次分表，请问这个是正常的吗；如下：
![image](https://user-images.githubusercontent.com/40423181/104267380-78b32500-54cc-11eb-9cf8-3663d5b2e739.png)

感谢解答

**Comment by freehere107** [comment]
正常的，没有什么问题。应该是每1,000,000 进行的分表。不是顺序是因为存在并发的问题，对同步没有影响
