### ISSUE TITLE
export rewards to .csv

### ISSUE THREAD

**Issue by gigen07** [itering/subscan-essentials#95]
i have tried to export rewards/slash to csv. I see that reward amount 0.000733 in .csv shown as 733
You can see two examples attached.

Tnx.

**Comment by freehere107** [comment]
The reward amount here has no precision, you can calculate it yourself

**Comment by gigen07** [comment]
why would you put that on a user to do? I mean, if you give the user the option to export data, then you should give the exact data into a file. don't you agree?

**Comment by freehere107** [comment]
We will fix this soon, thanks for feedback
