### ISSUE TITLE
插件相关的问题

### ISSUE THREAD

**Issue by zyjblockchain** [itering/subscan-essentials#96]
hello, 抱歉我又来了
问题：
          我现在使用该库来同步 polkadot 上的数据到数据库有block, event 和extrinsic， 我使用这三张表已经实现了通过指定的 extrinsic_hash 获取info 的功能。但是我现在还有一个需求是 通过 address 来查询 相关联的transfer。 在 extrinsic 表中只能查询到 address 作为from 的交易，如果是查询关联的所有转账交易需要在event 表中查询，现在我的event 是不支持这种索引的。

疑问：
        根据我的需求，我view 代码之后，并结合subscan 上有通过address 看到相关联的所有交易的功能，所以我看到了代码插件的这个功能。请问如果我需要实现这个功能，是要通过自己创建一个单独的插件来收集同步过来的所有event 中的`balances-transfer` 类型的事件存储到transfers table 中来使用吗。
         如果贵公司已经实现了transfer 插件功能，可以参考一下该插件的代码吗。非常感谢。

利益相关： 
       我们公司支持的 polkadot/kusama 钱包给用户默认的 explorer 是贵公司的 subscan explorer , 当时前同事使用同步区块数据的 polling 程序使用的是 polkascan 的 polling 代码，现在我在做的是把 polling 程序和默认 explorer 统一，所以使用该库的代码。希望能多多支持一下，非常感谢！

**Comment by freehere107** [comment]
多谢支持。插件 可以参考 https://github.com/itering/subscan-essentials/tree/master/plugins/balance
