### ISSUE TITLE
missing blocks - db timeout

### ISSUE THREAD

**Issue by sergeibadass** [itering/subscan-essentials#97]
Hi I am running subscan for node template and encounter following problems:

(1) Some blocks are missing from the chain_blocks table. The current block height of my chain has 700 more blocks then the rows in the database tables. In other words, 700 blocks are missing.

![image](https://user-images.githubusercontent.com/76840075/104676327-1fdcca00-5722-11eb-90f5-954c24d64d2f.png)

(2) I then check the log/substrate.log and found a lot of errors.
![image](https://user-images.githubusercontent.com/76840075/104676592-a2658980-5722-11eb-8f9b-5dfd4d63d682.png)

Could you kindly help to fix it? Thanks.

**Comment by freehere107** [comment]
@sergeibadass  Are you connected to the local MySQL? From the log, you can see that there is a MySQL connection problem. You can try to develop with docker-compose

**Comment by sergeibadass** [comment]
> @sergeibadass Are you connected to the local MySQL? From the log, you can see that there is a MySQL connection problem. You can try to develop with docker-compose

YES. and about 1% of blocks are missing. DB timeout only happens once in a while. 

Will the subscan daemon detect missing blocks and reinsert them? What's the simplest way to fix it?

**Comment by freehere107** [comment]
@sergeibadass Subscan essentials do not currently have such a feature, it may be added later.

**Comment by Fasih-KryptoMind** [comment]
@freehere107 is this feature added now in subscan essentials ?
Can I reindex all blocks or a specific block if its missed somehow ?

**Comment by freehere107** [comment]
@Fasih-KryptoMind ok, i will add some script to check missed block

**Comment by Fasih-KryptoMind** [comment]
Thankyou @freehere107. It will be quite helpful

**Comment by freehere107** [comment]
@Fasih-KryptoMind https://github.com/itering/subscan-essentials/blob/master/cmd/main.go#L82 maybe can help you

**Comment by lucgerrits** [comment]
@freehere107 Hi ! I had the same issue, some missing blocks here and there. Did you made that script ? It would be great :smile: , thanks.
