### ISSUE TITLE
数据库索引问题

### ISSUE THREAD

**Issue by zyjblockchain** [itering/subscan-essentials#98]
1. tabke 分表之后没有调用addIndex() 方法来为分表建立索引
![image](https://user-images.githubusercontent.com/40423181/104833649-2eb7ae00-58d5-11eb-8bf1-06c578e28bc2.png)
修改建议如上截图

**Comment by freehere107** [comment]
多谢反馈

**Comment by freehere107** [comment]
update https://github.com/itering/subscan-essentials/pull/129
